# Конфигурация конвертера FBX to VMDL
global_settings:
  # Масштаб модели (основная проблема S&Box)
  global_scale: 0.33
  # Целевое разрешение текстур
  texture_resolution: 1024
  # Пути к внешним инструментам
  paths:
    blender: "blender"  # или "C:/Program Files/Blender Foundation/Blender/blender.exe"
    imagemagick: "magick"

# Настройки LOD
lod:
  levels: [1.0, 0.5, 0.25, 0.1]  # Проценты полигонов для каждого LOD
  use_blender: true

# Настройки обработки текстур
textures:
  # Конвертация bump в normal
  bump_to_normal:
    scale: 3.0
    invert_x: false
    invert_y: false

  # Настройки detail текстур
  detail:
    scale_range: [4, 8]
    blend_smoothness: 0.3

# Настройки физической коллизии
physics:
  decimation_ratio: 0.05  # Агрессивное упрощение для коллизии